### ISSUE TITLE
Make Trup case insensitive to increase usability

### ISSUE THREAD

**Issue by medievalberries** [unixporn/trup#153] opened 2021-02-01 13:47 UTC
Currently, Trup views Polybar and polybar as two different objects, leading to !top returning both. Could the owners of Trup add case insensitivity into the code with (I'm a beginner with GoLang here, so correct me if I'm wrong) `strings.ToLower` or something? I know you can do this easily in pretty much any coding language, and it would greatly help !top become a more popular and less buggy feature.

If this is too difficult, ignore this. I'm by no means an expert coder with GoLang.

**Comment by eepykate** [comment] 2021-02-02 03:23
duplicate of #150?

part of synonyms would of course be case insensitivity, and it's just different wording for a similar problem.

**Closed as completed by eepykate** 2021-02-02 03:23 UTC
Labels: duplicate
